services:
  # Orchestrator: Mage AI
  mage:
    image: mageai/mageai:latest
    command: mage start ${MAGE_PROJECT_NAME}
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/${MAGE_PROJECT_NAME}
      MAGE_DATABASE_CONNECTION_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src
    restart: always

  # Database: PostgreSQL 
  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Cloud Emulator: LocalStack
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,kinesis,iam,sts
      - DEBUG=1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    name: supermarket_net